### PR TITLE
app-admin/eselect: update eselect support for PREFIX, Make it less br…

### PR DESCRIPTION
**Pull request by kiwifb**
…oken if at all.

Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by kiwifb** [comment]
Updated to the latest, I'll have to learn to do that a bit less violently.

**Comment by kiwifb** [comment]
Darn pulled against the wrong tree, will re-do.

**Comment by jlec** [comment]
I just checked the patch and it doesn't work. It tries to link into / instead of prefix.

**Comment by kiwifb** [comment]
I'll have to re-check. Without the patch you have double prefix all over the place.

**Comment by kiwifb** [comment]
OK I had forgotten a little something I didn't remember. It now links in the correct place but there are still issues. I had to emerge blas-reference twice before the provider was properly setup. By that I mean I had followed the following steps in my testing:
1) unmerge blas-reference (the only blas in my prefix at the moment)
2) rebuild eselect
3) re-install blas-reference.
```
>>> /home/frb15/gentoo/etc/env.d/alternatives/blas/reference/home/frb15/gentoo/usr/lib/pkgconfig/blas.pc -> ../../../../../../../../../../../../../../../../../../../../../../../../home/frb15/gentoo/usr/lib/pkgconfig/refblas.pc
 * Creating Alternative for blas
!!! Error: Missing required parameter 'provider'
exiting
>>> sci-libs/blas-reference-20131116-r1 merged.
```
the link quoted exists but `pkg-config blas --libs` doesn't find a blas provider.
4) install blas-reference again. This time everything is smooth except for the message
```
>>> Safely unmerging already-installed instance...
 * amd64: running fortran-int64_multilib_multibuild_wrapper my_pkg_prerm
 * eselect blas update reference returned 
No package files given... Grabbing a set.
```
but now `pkg-config` works:
```
pkg-config blas --libs
-lrefblas
```

**Comment by kiwifb** [comment]
Last commit somehow removed one needed `EROOT` restored it.

**Comment by heroxbd** [comment]
Could you please squash the commits so that they look cleaner for reviewing?

**Comment by kiwifb** [comment]
Sure, but I'll education on performing said squashing, can you point to some resources or a quick example?

**Comment by kiwifb** [comment]
Should have squashed before rebasing. I didn't realise that it would bury my commits.

**Comment by jlec** [comment]
What is the status of this PR?

**Comment by kiwifb** [comment]
I think it is obsolete now.

**Comment by jlec** [comment]
Closing it then

**Pull request closed without merging**
