### PR TITLE
sci-libs/openblas: Bump openblas to 0.2.19

### PR DESCRIPTION
**Pull request by kiwifb**
Package-Manager: portage-2.3.3

Note that this ebuild started its life on a ppc64 machine were I needed a higher version of openblas than in the overlay for proper support of my hardware. This is why this ebuild is keyworded ~ppc64.

### CODE REVIEW

**Comment by kiwifb** [comment]
I had forgotten a selection of upstreamed patch that could be of interest. I repeat all these have been merged upstream.

**Comment by heroxbd** [comment]
I see you have dropped openblas-0.2.11-openblas_config_header_same_between_ABIs.patch

What is the logic behind that?

**Comment by heroxbd** [comment]
@kiwifb What does '??die' mean?

**Comment by kiwifb** [comment]
@heroxbd Hum, I did all that stuff back in January early February so not everything is fresh in my mind :)
Obviously the patch didn't apply cleanly anymore and I believe that particular problem has been fixed upstream. But I like I said it is all a bit foggy now.
As for `??die` I don't know either. I am trying to figure out what kind of typo that could have been. I may have to check the layout of my keyboard at work.

**Comment by heroxbd** [comment]
@kiwifb Hi François. I was also puzzled by the patch, which had no explanations I could found.  So let's just drop it.

 For `??die`, I will fix them.

**Pull request merged**
