### PR TITLE
sci-visualization/surf-ice: added stable version

### PR DESCRIPTION
**Pull request by TheChymera**
Package-Manager: Portage-2.3.3, Repoman-2.3.1

### CODE REVIEW

**Comment by TheChymera** [comment]
@jlec The failure is unrelated to my PR - can you please merge?

**Comment by jlec** [comment]
@TheChymera Please fix the commented things.

**Comment by TheChymera** [comment]
What commented things?

It seems to me like this is the build error:

```
 !!! .travis.yml outdated! Update available https://github.com/mrueg/repoman-travis 
RepoMan scours the neighborhood...
 * ERROR: sys-cluster/ganglia_jobmonarch-0.3.1::science failed (depend phase):
 *   depend.php.eclass could not be found by inherit()
 * 
 * Call stack:
 *                         ebuild.sh, line 611:  Called source '/home/travis/build/gentoo-science/sci/travis-overlay/sys-cluster/ganglia_jobmonarch/ganglia_jobmonarch-0.3.1.ebuild'
 *   ganglia_jobmonarch-0.3.1.ebuild, line   9:  Called inherit 'eutils' 'webapp' 'depend.php' 'python-r1'
 *                         ebuild.sh, line 284:  Called die
 * The specific snippet of code:
 *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=sys-cluster/ganglia_jobmonarch-0.3.1::science'`,
 * the complete build log and the output of `emerge -pqv '=sys-cluster/ganglia_jobmonarch-0.3.1::science'`.
 * Working directory: '/home/travis/build/gentoo-science/sci/portage-portage-2.3.3/pym'
 * S: '/var/tmp/portage/sys-cluster/ganglia_jobmonarch-0.3.1/work/ganglia_jobmonarch-0.3.1'
  IUSE.missing [fatal]          16
```

It doesn't look related to this package  not has anybody left any comments.

**Comment by timeraider4u** [comment]
@TheChymera I agree with you that the travis-errors are not connected to your ebuild. Nethertheless you might remove the $Id$ line in your local repository and commit+push this change to Github. This way your pull-request will be updated automatically and Travis CI would be re-triggered.

**Pull request merged**
