### PR TITLE
add metis dependency #408

### LINKED ISSUE #408: sci-mathematics/netgen depends on metis
Got an error while compiling parallelmesh.cpp due to metis

```
/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../..  -I/usr/local/include -DMETIS -I../../libsrc/include  -I/usr/include/togl-1.7  -march=native -O2 -pipe -mavx -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mcx16 -mpopcnt -DPARALLEL -c -o paralleltop.lo paralleltop.cpp
parallelmesh.cpp:13:19: fatal error: metis.h: No such file or directory
 #include <metis.h>
                   ^
compilation terminated.
Makefile:571: recipe for target 'parallelmesh.lo' failed
make[3]: *** [parallelmesh.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: compile:  x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../.. -I/usr/local/include -DMETIS -I../../libsrc/include -I/usr/include/togl-1.7 -march=native -O2 -pipe -mavx -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mcx16 -mpopcnt -DPARALLEL -c paralleltop.cpp  -fPIC -DPIC -o .libs/paralleltop.o
make[3]: Leaving directory '/var/tmp/portage/sci-mathematics/netgen-5.0.0/work/netgen-5.0.0/libsrc/meshing'
Makefile:394: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/sci-mathematics/netgen-5.0.0/work/netgen-5.0.0/libsrc'
Makefile:440: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/sci-mathematics/netgen-5.0.0/work/netgen-5.0.0'
Makefile:371: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: sci-mathematics/netgen-5.0.0::science failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=sci-mathematics/netgen-5.0.0::science'`,
 * the complete build log and the output of `emerge -pqv '=sci-mathematics/netgen-5.0.0::science'`.
 * The complete build log is located at '/var/tmp/portage/sci-mathematics/netgen-5.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/netgen-5.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-mathematics/netgen-5.0.0/work/netgen-5.0.0'
 * S: '/var/tmp/portage/sci-mathematics/netgen-5.0.0/work/netgen-5.0.0'

>>> Failed to emerge sci-mathematics/netgen-5.0.0, Log file:

>>>  '/var/tmp/portage/sci-mathematics/netgen-5.0.0/temp/build.log'

 * Messages for package sci-mathematics/netgen-5.0.0:

 * ERROR: sci-mathematics/netgen-5.0.0::science failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=sci-mathematics/netgen-5.0.0::science'`,
 * the complete build log and the output of `emerge -pqv '=sci-mathematics/netgen-5.0.0::science'`.
 * The complete build log is located at '/var/tmp/portage/sci-mathematics/netgen-5.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/netgen-5.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-mathematics/netgen-5.0.0/work/netgen-5.0.0'
 * S: '/var/tmp/portage/sci-mathematics/netgen-5.0.0/work/netgen-5.0.0'

```

Metis is installed:
```
$ emerge -s metis
  
[ Results for search key : metis ]
Searching...

*  sci-libs/metis
      Latest version available: 4.0.3
      Latest version installed: [ Not Installed ]
      Size of files: 511 KiB
      Homepage:      http://www-users.cs.umn.edu/~karypis/metis/metis/
      Description:   A package for unstructured serial graph partitioning
      License:       free-noncomm

*  sci-libs/parmetis
      Latest version available: 3.2.0
      Latest version installed: 3.2.0
      Size of files: 5 168 KiB
      Homepage:      http://www-users.cs.umn.edu/~karypis/metis/parmetis/
      Description:   Parallel graph partitioner
      License:       free-noncomm

```

But metis.h is located /usr/include/metis and not /usr/include

### PR DESCRIPTION
**Pull request by apieum**
Added dependency with metis and metis include directory

### CODE REVIEW

**Comment by marbre** [comment]
Plesse check the Travis output to check for errors:
[fatal]     2
   sci-mathematics/netgen/netgen-5.0.0.ebuild: DEPEND: missing whitespace around '(' at '(sci-libs/parmetis', token 6
   sci-mathematics/netgen/netgen-5.0.0.ebuild: RDEPEND: missing whitespace around '(' at '(sci-libs/parmetis', token 6
You should always use repoman to check your ebuild and use repo-commit instead of git. Please the the contribution instructions.

**Comment by apieum** [comment]
Sorry, I would fix it fast, but I should have read how to contribute before sending PR.
I've seen my mistake but it still can't be compiled on my system (x86_64), I've found other errors, but it definetly stop due to mpi.

**Comment by marbre** [comment]
First, is metis || parmetis mandatory or is it an optional dependency?

Second, I think you're using parmetis. If you've trouble with mpi, is parmetis compiled with the `mpi` use flag?

**Comment by apieum** [comment]
There is no mpi flag for parmetis, it is compiled for openFOAM (no mpi flag) which requires paraview which has mpi flag but deactivated (can't compile with it).

Metis is mandatory, but I need to test without "mpi" flag to confirm if it is specific to mpi or not.
That's why I've not fixed immediately my mistake, I've underestimated the problem and need to investigate a bit more.
metis and parmetis block each other, that's why there is an OR block, if you want openfoam, you can't have metis.

**Comment by apieum** [comment]
```
$ equery d mpi
 * These packages depend on mpi:
dev-libs/boost-1.55.0-r2 (mpi ? virtual/mpi[cxx,threads])
dev-python/mpi4py-1.3.1 (virtual/mpi)
                        (test ? virtual/mpi[romio])
sci-libs/fftw-3.3.4 (mpi ? virtual/mpi)
sci-libs/hdf5-1.8.14-r1 (mpi ? virtual/mpi[romio])
sci-libs/openfoam-2.3.1 (virtual/mpi)
sci-libs/parmetis-3.2.0 (virtual/mpi)
sci-libs/parmgridgen-1.0 (virtual/mpi)
sci-libs/scotch-6.0.0 (mpi ? virtual/mpi)
sci-visualization/paraview-4.1.0-r2 (mpi ? virtual/mpi[cxx,romio])
```

**Pull request merged**
